# Generated by Django 3.1.3 on 2020-11-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='descriopcion',
            new_name='descripcion',
        ),
    ]
