# Generated by Django 3.1.3 on 2020-11-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20201116_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='libre',
            new_name='Libro',
        ),
    ]
