# Generated by Django 3.1.3 on 2020-11-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_auto_20201116_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
