# Generated by Django 3.1.3 on 2020-11-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0009_auto_20201116_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
